apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-postgresql
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s/data/postgresql"
